version: '0.1'
services:
  backend: 
    build: ./backend
    ports:
      -"3000:3000"
    env_file:
      -./backend/.env

  frontend:
    build: ./frontend
    ports:
      -"80:80"
    depends_on:
      - backend

